### ISSUE TITLE
Notifications with long text push off screen

### ISSUE THREAD

**Issue by karpstrucking** [barrykooij/wp-notification-center#4]
The notifications I run into in the wild are quite often more than a few words, more like a few sentences at least. It looks like the default admin bar styling doesn't play well with that, causing the text to push off screen rather than wrapping:

![image](https://cloud.githubusercontent.com/assets/999261/9829177/0e7146a0-58c8-11e5-8b0f-2d621d2f73db.png)

**Comment by swissspidy** [comment]
The text could be truncated using CSS, e.g. like this:

``` css
.notification {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

The full text could be shown on hover or something else.

Another possibility is to add word breaks so the item just gets taller instead of wider.
