### ISSUE TITLE
Support for newer notice CSS classes

### ISSUE THREAD

**Issue by glueckpress** [barrykooij/wp-notification-center#6]
Currently notifications within the manager only get a colored border when [`updated`, `update-nag` or `error`](https://github.com/barrykooij/wp-notification-center/blob/e013bbf2f70ea07fd2e1b86235a3089d8ab0d67a/assets/css/scss/wp-notification-center.scss#L17-L25) are applied as classes. There are more notification classes in WordPress, though, that should be supported as well:

``` css
.notice-success,
div.updated {
    border-color: #7ad03a;
}

.notice-warning {
    border-color: #ffba00;
}

.notice-error,
div.error {
    border-color: #dd3d36;
}

.notice-info {
    border-color: #00a0d2;
}
```

https://github.com/WordPress/WordPress/blob/f446d01b4cb523015ced5e2660c40a46aeadb1e2/wp-admin/css/common.css#L1339-L1355
